# Generated by Django 4.2.4 on 2023-09-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userinfo_delete_custumerinfo_delete_user_detaile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
